### ISSUE TITLE
Docker: Worker failed to boot

### ISSUE THREAD

**Issue by cplieger** [Babalion/integrityCheckarr#8]
```
integrity-checkarr | [2023-01-30 01:26:23 +0000] [1] [INFO] Starting gunicorn 20.1.0
integrity-checkarr | [2023-01-30 01:26:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:8050 (1)
integrity-checkarr | [2023-01-30 01:26:23 +0000] [1] [INFO] Using worker: sync
integrity-checkarr | [2023-01-30 01:26:23 +0000] [7] [INFO] Booting worker with pid: 7
integrity-checkarr | [2023-01-30 01:26:23 +0000] [8] [INFO] Booting worker with pid: 8
integrity-checkarr | [2023-01-30 01:26:24 +0000] [7] [ERROR] Exception in worker process
integrity-checkarr | Traceback (most recent call last):
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_                                                                                       worker
integrity-checkarr |     worker.init_process()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in i                                                                                       nit_process
integrity-checkarr |     self.load_wsgi()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in l                                                                                       oad_wsgi
integrity-checkarr |     self.wsgi = self.app.wsgi()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
integrity-checkarr |     self.callable = self.load()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in loa                                                                                       d
integrity-checkarr |     return self.load_wsgiapp()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in loa                                                                                       d_wsgiapp
integrity-checkarr |     return util.import_app(self.app_uri)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_ap                                                                                       p
integrity-checkarr |     mod = importlib.import_module(module)
integrity-checkarr |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
integrity-checkarr |     return _bootstrap._gcd_import(name[level:], package, level)
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
integrity-checkarr |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
integrity-checkarr |   File "/dashboard.py", line 23, in <module>
integrity-checkarr |     moviesListOld = pd.read_csv(LIST_PATH, index_col=0, keep_default_na=False,
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in                                                                                        wrapper
integrity-checkarr |     return func(*args, **kwargs)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in                                                                                        wrapper
integrity-checkarr |     return func(*args, **kwargs)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950,                                                                                        in read_csv
integrity-checkarr |     return _read(filepath_or_buffer, kwds)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605,                                                                                        in _read
integrity-checkarr |     parser = TextFileReader(filepath_or_buffer, **kwds)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442,                                                                                        in __init__
integrity-checkarr |     self._engine = self._make_engine(f, self.engine)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735,                                                                                        in _make_engine
integrity-checkarr |     self.handles = get_handle(
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_ha                                                                                       ndle
integrity-checkarr |     handle = open(
integrity-checkarr | FileNotFoundError: [Errno 2] No such file or directory: '/Logs/movieFileList.csv'
integrity-checkarr | [2023-01-30 01:26:24 +0000] [7] [INFO] Worker exiting (pid: 7)
integrity-checkarr | gunicorn version:20.1.0
integrity-checkarr | [2023-01-30 01:26:24 +0000] [8] [ERROR] Exception in worker process
integrity-checkarr | Traceback (most recent call last):
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_                                                                                       worker
integrity-checkarr |     worker.init_process()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in i                                                                                       nit_process
integrity-checkarr |     self.load_wsgi()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in l                                                                                       oad_wsgi
integrity-checkarr |     self.wsgi = self.app.wsgi()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
integrity-checkarr |     self.callable = self.load()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in loa                                                                                       d
integrity-checkarr |     return self.load_wsgiapp()
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in loa                                                                                       d_wsgiapp
integrity-checkarr |     return util.import_app(self.app_uri)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_ap                                                                                       p
integrity-checkarr |     mod = importlib.import_module(module)
integrity-checkarr |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
integrity-checkarr |     return _bootstrap._gcd_import(name[level:], package, level)
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
integrity-checkarr |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
integrity-checkarr |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
integrity-checkarr |   File "/dashboard.py", line 23, in <module>
integrity-checkarr |     moviesListOld = pd.read_csv(LIST_PATH, index_col=0, keep_default_na=False,
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in                                                                                        wrapper
integrity-checkarr |     return func(*args, **kwargs)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in                                                                                        wrapper
integrity-checkarr |     return func(*args, **kwargs)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950,                                                                                        in read_csv
integrity-checkarr |     return _read(filepath_or_buffer, kwds)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605,                                                                                        in _read
integrity-checkarr |     parser = TextFileReader(filepath_or_buffer, **kwds)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442,                                                                                        in __init__
integrity-checkarr |     self._engine = self._make_engine(f, self.engine)
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735,                                                                                        in _make_engine
integrity-checkarr |     self.handles = get_handle(
integrity-checkarr |   File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_ha                                                                                       ndle
integrity-checkarr |     handle = open(
integrity-checkarr | FileNotFoundError: [Errno 2] No such file or directory: '/Logs/movieFileList.csv'
integrity-checkarr | [2023-01-30 01:26:24 +0000] [8] [INFO] Worker exiting (pid: 8)
integrity-checkarr | gunicorn version:20.1.0
integrity-checkarr | [2023-01-30 01:26:24 +0000] [1] [WARNING] Worker with pid 8 was terminated due to signal                                                                                        15
integrity-checkarr | [2023-01-30 01:26:25 +0000] [1] [INFO] Shutting down: Master
integrity-checkarr | [2023-01-30 01:26:25 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by cplieger** [comment]
Happy to test new build or potential fixes, let me know!

**Comment by dbroome1978** [comment]
I'm assuming this project was canceled but I am getting the same erorr. Are we suppose to create the movieFileList.cvs? I don't see that in the setup notes
